name: Test with node
on:
  push:
    paths:
      - "**/*.js"
      - "package*.*"
  pull_request:
    paths:
      - "**/*.js"
jobs:
  testingWithNode:
    strategy:
      matrix:
        version: [18, lts/*, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Working version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Fuentes
        uses: actions/checkout@v4
      - name: test
        working-directory: code/JS
        run: npm ci && npm test
