name: Test perl code
on:
  push:
    paths:
      - "**/*.pl"
      - "**/*.pm"
      - "**/*.t"
jobs:
  test-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - App::cpanminus
          export PATH=$HOME/perl5/bin:$PATH
      - name: Install dependencies
        run: |
          cpanm --installdeps .
      - name: Test with prove
        run: cd code&& prove -l
