name: "Test zig"
on:
    push:
        paths:
        - code/zig
jobs:
    test-zig:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Zig
          with:
            version: 0.11.0
          uses: goto-bus-stop/setup-zig@v2
        - name: Lint zig
          working-directory: code/zig
          run: zig fmt --check --color on
        - name: Test zig
          working-directory: code/zig
          run: zig build test